name: code-coverage
on: [push, pull_request]
jobs:
    check:
        outputs:
            run_job: ${{ steps.check_files.outputs.run_job }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              with:
                  fetch-depth: 2
            - name: check modified files
              id: check_files
              run: |
                  echo "=============== List Modified Files ==============="
                  git diff --name-only HEAD^ HEAD

                  echo "========== Check Paths of Modified Files =========="
                  git diff --name-only HEAD^ HEAD &gt; files.txt
                  while IFS= read -r file
                  do
                    echo $file
                    if [[ $file != force-app/main/* ]]; then
                      echo "This modified file is not under the 'force-app/main' folder."
                      echo "::set-output name=run_job::false"
                      break
                    else
                      echo "::set-output name=run_job::true"
                    fi
                  done &lt; files.txt
    build:
        needs: check
        if: needs.check.outputs.run_job == 'true'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Install Dependencies
              run: npm install sfdx-cli
            - name: Populate auth file
              run: 'echo "${{ secrets.SALESFORCE_AUTH_URL }}" > ./SALESFORCE_AUTH_URL.txt'
            - name: Authenticate Dev Hub
              run: "node_modules/sfdx-cli/bin/run force:auth:sfdxurl:store -f ./SALESFORCE_AUTH_URL.txt -a devhub -d"
            - name: Create Scratch Org
              run: node_modules/sfdx-cli/bin/run force:org:create --targetdevhubusername devhub --setdefaultusername --definitionfile config/project-scratch-def.json --setalias ciorg --durationdays 1
            - name: Deploy source
              run: node_modules/sfdx-cli/bin/run force:source:push
            - name: Run Apex tests
              run: node_modules/sfdx-cli/bin/run force:apex:test:run --codecoverage --resultformat human -d ./
            - name: Upload code coverage for Apex to Codecov.io
              uses: codecov/codecov-action@v2
              with:
                  flags: Apex
            - name: Delete Scratch Org
              run: node_modules/sfdx-cli/bin/run force:org:delete --noprompt
