name: code-coverage
on: 
    pull_request: { branches: [master] }
jobs:
    check:
        runs-on: ubuntu-latest
        outputs:
            files-changed: ${{ steps.check-changed-files.outputs.any_changed }}
        steps:
            - uses: actions/checkout@v3
              with:
                fetch-depth: 2
            - id: check-changed-files
              name: Get changed files in the force-app/main folder
              uses: tj-actions/changed-files@v32.0.0
              with:
                files: |
                    force-app/main/**
    build:
        needs: check
        if: needs.check.outputs.files-changed == 'true'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Install Dependencies
              run: npm install sfdx-cli
            - name: Populate auth file
              run: 'echo "${{ secrets.SALESFORCE_AUTH_URL }}" > ./SALESFORCE_AUTH_URL.txt'
            - name: Authenticate Dev Hub
              run: "node_modules/sfdx-cli/bin/run force:auth:sfdxurl:store -f ./SALESFORCE_AUTH_URL.txt -a devhub -d"
            - name: Create Scratch Org
              run: node_modules/sfdx-cli/bin/run force:org:create --targetdevhubusername devhub --setdefaultusername --definitionfile config/project-scratch-def.json --setalias ciorg --durationdays 1
            - name: Deploy source
              run: node_modules/sfdx-cli/bin/run force:source:push
            - name: Run Apex tests
              run: node_modules/sfdx-cli/bin/run force:apex:test:run --codecoverage --resultformat human -d ./
            - name: Upload code coverage for Apex to Codecov.io
              uses: codecov/codecov-action@v2
              with:
                  flags: Apex
            - name: Delete Scratch Org
              run: node_modules/sfdx-cli/bin/run force:org:delete --noprompt
